### ISSUE TITLE
Support for strings starting with NODE_ENV

### ISSUE THREAD

**Issue by jontelm** [ctavan/node-getenv#14]
Hi,

What about making it possible to add a base of string so example
```
NODE_ENV=PRODUCTION

getenv("RANDOM") will look for PRODUCTION_RANDOM

NODE_ENV=STAGING

getenv("RANDOM") will look for STAGING_RANDOM
```

**Comment by ctavan** [comment]
Hi @jontelm, thanks for proposing this idea. What is the exact use case for this?

As stated in the README of this module, it was built to facilitate implementation of the [Twelve Factor Apps](https://www.12factor.net/) principles. The idea behind [part III. of a Twelve Factor App](https://www.12factor.net/config) is to store all configuration in environment variables that have the same name but different _values_ in the different environments.

Having different environment variable _names_ in different environments would be against this fundamental idea.

**Comment by jontelm** [comment]
It's just that when you working on different systems it's maybe good to get an extra reminders that what env you are in so you can be more sure you are setting the right env variables..and in this case if will fail if it was wrong. Just an idea for me that connects to different env in the terminal and it's hard to difference a config to another when it's the same names on all env variables.

**Comment by ctavan** [comment]
To be honest I believe that in the concept of Twelve Factor Apps it's a crucial idea to have the same environment variable _names_ with different _values_ in different environments.

The good thing about environment variables is that they are usually `undefined` by default and this library has explicitly been designed to throw an error if a requested environment variable is not defined in the current environment. So in order to solve the issue you are describing above I'd rather suggest to rely on variables being defined or not in certain environments rather than different naming of environment variables in different environments. After all having a `PRODUCTION_RANDOM` variable being defined in a staging environment doesn't make a lot of sense and could in contrary lead to a lot of confusion (or even worse, when thinking about secrets one could be tempted to always specify the production secrets for all environments which would be a really bad idea!).

I believe adding a feature like you are proposing might be solving some specific other problem but it would run counter the Twelve Factor idea and I will therefore not include a feature like this.

If I'm still missing something feel free to propose code changes as a pull request and provide more hands-on examples of your use case, I'll be happy to review those.
