### ISSUE TITLE
Undefined gets cast as 'undefined'

### ISSUE THREAD

**Issue by pdufour** [ctavan/node-getenv#17]

**Comment by ctavan** [comment]
Can you give an example of where this happens?

**Comment by ctavan** [comment]
Please provide additional information if this is still a problem.

**Comment by nltncsr** [comment]
It happens also if you use `null` for fallback. For instance, if you have the following piece of code:
```js
getEnv('SOME_ENV_VAR', null);
```

it returns `'null'`, and I believe that's because passing a fallback falls into [that line](https://github.com/ctavan/node-getenv/blob/master/index.js#L25) that resolves the types `string` and `null` gives `'null'`:

> '' + null === 'null' // true

**Comment by ctavan** [comment]
Please note that `getenv()` is equivalent to `getenv.string()` which, by design, always returns a string (or throws). If you want more subtle "nullish" value handling I think you will most probably have to implement it on your own since it's hard to find canonical semantics here that work for everyone.

You could for example do:

```js
env.disableErrors();
const someVar = env('SOME_ENV_VAR') || null;
```

to cast falsy values (`undefined` or the empty string `''` in the case of `env.string()`) to `null`.

**Comment by nltncsr** [comment]
That makes sense if it's for the design of the package, I was worried if it was buggy or something. I would be strict for respecting the types instead of the string representation of the fallback.
Thanks for the answer 😄

**Comment by Alexandru-Pirvu** [comment]
undefined is a valid state though..
