### ISSUE TITLE
Support "1" and "yes" for getenv.bool

### ISSUE THREAD

**Issue by gabriel** [ctavan/node-getenv#5]
It would be nice to support "1" or "yes" for getenv.bool.

Currently it throws an error "[Error: GetEnv.NoBoolean: 1 is not a boolean.]" in this case.

Or maybe a flag to support less strict value?

**Comment by ctavan** [comment]
I think we shouldn't change the default behavior since some people might rely on the strict check at the moment, but I definitely see value in your suggestion. So feel free to provide a pull request which implements the suggested functionality (using a flag or potentially something `getenv.boolish()`)!

**Comment by chrisnojima** [comment]
@gabriel I implemented this here: https://github.com/keybase/node-getenv

**Comment by ctavan** [comment]
@chrisnojima cool, how about changing you patch to be backwards-compatible and then issuing a pull-request? I'm happy to merge your change then and you could get the library from npm then.

**Comment by chrisnojima** [comment]
Done: https://github.com/ctavan/node-getenv/pull/6
